apiVersion: batch/v1
kind: Job
metadata:
  name: ${{ values.name }}-create-jenkins-job
spec:
  backoffLimit: 100
  template:
    spec:
      containers:
      - name: create-webhook
        command:
          - /bin/bash
          - '-c'
          - |
            set -x
            ansible-playbook -i localhost /scripts/playbook.yaml \
            -e jenkins_admin_user=$(cat /secrets/jenkins/username) \
            -e jenkins_admin_password=$(cat /secrets/jenkins/password) \
            -e jenkins_job=${{ values.name }}
        image: quay.io/agnosticd/ee-multicloud:latest
        volumeMounts:
          - mountPath: /scripts
            name: jenkins-job-config
          - mountPath: /secrets/jenkins
            name: jenkins-admin-credentials
      restartPolicy: Never
      volumes:
      - name: jenkins-job-config
        configMap:
          name: ${{ values.name }}-jenkins-job-config
      - name: jenkins-admin-credentials
        secret:
          secretName: jenkins-admin-credentials
