apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: provisioning-data
  description: Provisioning data from demo.redhat.com
  labels:
    ocp-apps-domain: {{ ocp_apps_domain }}
    guid: {{ guid }}
spec:
  type: service
  lifecycle: production
  owner: tssc
